import type { CategoriaInfo } from "./types";

export const CATEGORIAS_INCIDEAS: CategoriaInfo[] = [
  {
    id: "territorio",
    nombre: "Territorio",
    descripcion: "Identificación administrativa, límites, superficie, núcleos, topografía, usos del suelo e hidrología.",
    nivel_automatizacion: "alta",
    campos_obligatorios: ["codigo_ine", "nombre_oficial", "geometria"],
    campos_deseables: ["superficie", "altitud", "pendiente", "usos_suelo", "hidrologia"],
    caducidad_meses: 12,
  },
  {
    id: "poblacion",
    nombre: "Población",
    descripcion: "Padrón, evolución demográfica, población por núcleo, densidad, estructura por edad y población estacional.",
    nivel_automatizacion: "alta",
    campos_obligatorios: ["codigo_ine", "poblacion_empadronada"],
    campos_deseables: ["evolucion", "densidad", "estructura_edad", "poblacion_estacional"],
    caducidad_meses: 12,
  },
  {
    id: "necesidades_especiales",
    nombre: "Personas con necesidades especiales",
    descripcion: "Información agregada sobre movilidad reducida, discapacidades, dependencia y necesidades de evacuación.",
    nivel_automatizacion: "baja",
    campos_obligatorios: ["codigo_ine", "nivel_territorial"],
    campos_deseables: ["movilidad_reducida", "discapacidad_visual", "discapacidad_auditiva", "dependencia"],
    caducidad_meses: 24,
  },
  {
    id: "animales",
    nombre: "Animales de compañía",
    descripcion: "Estimación de animales, hogares con animales, recursos veterinarios y centros de acogida.",
    nivel_automatizacion: "baja",
    campos_obligatorios: ["codigo_ine", "tipo_recurso"],
    campos_deseables: ["estimacion_animales", "hogares_con_animales", "clinicas_veterinarias"],
    caducidad_meses: 12,
  },
  {
    id: "infraestructuras",
    nombre: "Infraestructuras y movilidad",
    descripcion: "Carreteras, ferrocarril, transporte público, puertos y accesos estratégicos.",
    nivel_automatizacion: "alta",
    campos_obligatorios: ["codigo_ine", "tipo_infraestructura"],
    campos_deseables: ["titularidad", "puntos_kilometricos", "tuneles", "puentes"],
    caducidad_meses: 12,
  },
  {
    id: "equipamientos",
    nombre: "Equipamientos públicos",
    descripcion: "Sanidad, educación, servicios sociales, cultura, deporte y administración.",
    nivel_automatizacion: "media",
    campos_obligatorios: ["codigo_ine", "tipo_equipamiento", "titularidad"],
    campos_deseables: ["capacidad", "accesibilidad", "horario", "contacto_publico"],
    caducidad_meses: 12,
  },
  {
    id: "servicios_basicos",
    nombre: "Servicios básicos",
    descripcion: "Abastecimiento, saneamiento, electricidad, gas, telecomunicaciones y residuos.",
    nivel_automatizacion: "baja",
    campos_obligatorios: ["codigo_ine", "tipo_servicio", "gestor"],
    campos_deseables: ["etap", "edar", "depositos", "hidrantes"],
    caducidad_meses: 12,
  },
  {
    id: "riesgos",
    nombre: "Riesgos",
    descripcion: "Inundación, incendio forestal, sísmico, mercancías peligrosas y otros riesgos.",
    nivel_automatizacion: "alta",
    campos_obligatorios: ["codigo_ine", "tipo_riesgo", "fuente"],
    campos_deseables: ["nivel_riesgo", "cartografia", "poblacion_expuesta"],
    caducidad_meses: 24,
  },
  {
    id: "medios_recursos",
    nombre: "Medios y recursos",
    descripcion: "CECOPAL, PMA, bomberos, policía, vehículos, maquinaria y recursos movilizables.",
    nivel_automatizacion: "baja",
    campos_obligatorios: ["codigo_ine", "tipo_recurso", "titularidad"],
    campos_deseables: ["vehiculos", "personal", "contacto_operativo"],
    caducidad_meses: 12,
  },
  {
    id: "evacuacion",
    nombre: "Evacuación y albergue",
    descripcion: "Sectores de evacuación, puntos de encuentro, albergues y capacidad de acogida.",
    nivel_automatizacion: "baja",
    campos_obligatorios: ["codigo_ine", "sector", "tipo_recurso"],
    campos_deseables: ["capacidad", "accesibilidad", "zona_animales"],
    caducidad_meses: 12,
  },
  {
    id: "calidad",
    nombre: "Calidad y vigencia",
    descripcion: "Control de calidad, caducidad, duplicados y validación de registros.",
    nivel_automatizacion: "media",
    campos_obligatorios: ["codigo_ine"],
    campos_deseables: ["estado_validacion", "fecha_validacion", "unidad_validadora"],
  },
  {
    id: "exportaciones",
    nombre: "Exportaciones",
    descripcion: "XLSX, CSV, GeoJSON, Word y paquetes QGIS con trazabilidad completa.",
    nivel_automatizacion: "alta",
    campos_obligatorios: ["codigo_ine"],
    campos_deseables: ["formato", "categoria", "licencia"],
  },
];

export function getCategoria(id: string): CategoriaInfo | undefined {
  return CATEGORIAS_INCIDEAS.find((c) => c.id === id);
}
